# Generated by Django 5.2 on 2025-12-03 18:06

import django.db.models.deletion
import zakaz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('closed', models.DateTimeField(null=True)),
                ('sh', models.CharField(max_length=3)),
                ('year', models.PositiveSmallIntegerField()),
                ('group', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Pricelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=64)),
                ('formats', models.JSONField()),
                ('themes', models.JSONField()),
                ('bonus', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('ordered', models.DateTimeField(null=True)),
                ('order', models.JSONField(default=dict, null=True)),
                ('img', models.FileField(upload_to=zakaz.models.upload_blank)),
                ('imgname', models.CharField(default='', max_length=64)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='zakaz.album')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=128)),
                ('pricelist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='zakaz.pricelist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='zakaz.session'),
        ),
    ]
