# Generated by Django 5.2 on 2025-12-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blank',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
