# Generated by Django 5.2 on 2025-12-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0002_blank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
