# Generated by Django 5.2 on 2025-12-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0003_pricelist_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='blank',
            name='orders',
            field=models.JSONField(default=list, null=True),
        ),
    ]
