# Generated by Django 5.2 on 2026-03-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0005_school_album_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='blank',
            name='is_prep',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
